services:

  localstack:
    image: localstack/localstack:3
    volumes:
      - "./scripts/localstack/init:/etc/localstack/init/ready.d"
      - "./scripts/localstack/wait:/scripts/wait"
    environment:
      # this ensures that opensearch domain endpoints have the pattern
      # http://localstack:4566/<engine-type>/<region>/<domain-name>;
      # see https://docs.localstack.cloud/user-guide/aws/opensearch/
      OPENSEARCH_ENDPOINT_STRATEGY: path

      OPENSEARCH_DOMAIN: rd-demo

      AWS_DEFAULT_REGION: eu-west-2
      S3_BUCKET: mojap-rd
      S3_KEY_PREFIX: demo_folder
    healthcheck:
      test: bash /scripts/wait/healthcheck.sh
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 4566:4566
    restart: unless-stopped
