apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api # this should match the pod label in frontend-deployment.yml
  ports:
    - name: https
      port: 8081
      targetPort: 8081
