name: Test Package
on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04 # pin to avoid breaking changes when runner images update latest
    timeout-minutes: 15
    strategy:
      fail-fast: false # ensures entire python version matrix executes to completion
      matrix:
        python-version: ["3.9", "3.12"]
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'

    - name: pre-commit
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # sha for v4.2.1
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: |
        pre-commit install
        pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
        pre-commit run --show-diff-on-failure --color=always --all-files
    - name: Run Tests and Generate Coverage Report
      env:
        PY_COLORS: 1
      run: |
        coverage run -m pytest
        coverage xml
        coverage report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 #v4.6.0
      with:
        file: ./coverage.xml
        flags: unittests
        verbose: true
        token: ${{secrets.CODECOV_TOKEN}}
